# Generated by Django 3.0.1 on 2021-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
