# Generated by Django 3.0.1 on 2021-01-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
