# Generated by Django 3.0.1 on 2021-01-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
