# Generated by Django 3.0.1 on 2021-01-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_albumsongs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumSongs',
        ),
    ]
