# Generated by Django 3.0.1 on 2021-01-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_delete_albumsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.TextField(blank=True, max_length=250, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Album')),
            ],
        ),
    ]
