# Generated by Django 3.0.1 on 2021-01-27 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_albumsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albumsongs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumsongs', to='products.Album'),
        ),
    ]
